name: CI/CD
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node: [14, 16]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Check-out repository
      uses: actions/checkout@v4 
    - name: Installing dependencies
      run: npm install
    - name: Run tests
      run: npm test